### ISSUE TITLE
Missing description for prerequisites

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-python#10]
[Obviously](https://github.com/lgrahl/threema-msgapi-sdk-python/blob/cdf8bb8e4f735dbe6d0daf0be364f69a99d609e2/threema/gateway/__init__.py#L26) you use [`requests`](https://pypi.python.org/pypi/requests) but in the Readme it is not listed under "[Prerequisites](https://github.com/lgrahl/threema-msgapi-sdk-python#prerequisites)", so you should add it there as a required library:

```
pip install requests
```

~~And you also - obviously - [use](https://github.com/lgrahl/threema-msgapi-sdk-python/blob/cdf8bb8e4f735dbe6d0daf0be364f69a99d609e2/threema/gateway/__init__.py#L27-L28) [`libnacl`](https://pypi.python.org/pypi/libnacl) so you should also mention it.~~
~~`pip install libnacl`~~

**Comment by rugk** [comment]
Ah just read:

> The dependency libnacl will be installed automatically. However, you may need to install libsodium for libnacl to work. 

So only requests may be missing. Or is this also installed automatically?

**Comment by lgrahl** [comment]
[setup.py](https://github.com/lgrahl/threema-msgapi-sdk-python/blob/3274e3185844a7a836a2dc5360425a3663a54101/setup.py#L25) takes care of dependencies. `libnacl` is only listed because it requires an external library.
