### ISSUE TITLE
Padding with PRNG

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-python#12]
[For encrypting (text) messages](https://github.com/lgrahl/threema-msgapi-sdk-python/blob/master/threema/gateway/e2e.py#L47-L51) a padding it added. However this uses [a pseudo-random-number generator](https://docs.python.org/2/library/random.html), which is cryptographically not secure.
[In the Threema Whitepaper](https://threema.ch/press-files/2_documentation/cryptography_whitepaper.pdf#page9) (page 9) the purpose of this is described:

> ##### Padding
> 
> In order to thwart attempts to guess the content of short messages by looking at the amount of data, Threema adds a random amount of PKCS#7 padding to each message before end-to-end encryption.

So it is not that serious if this is weak and [does not affect the security of NaCl/Libsodium](https://github.com/jedisct1/libsodium-php/issues/71#issuecomment-166356772) as it is just an additional feature, but in the [Threema Whitepaper it is claimed](https://threema.ch/press-files/2_documentation/cryptography_whitepaper.pdf#page8) (page 8) that the clients (aka the Threema app) use real RNG for "Padding amount determination", so obviously this is a different implementation there.

[I've asked on Stackexchange](https://crypto.stackexchange.com/questions/31436/is-pkcs7-padding-generated-with-a-pseudo-random-number-generator-okay) whether this is a problem, but also when it is not there are no arguments against using a real cryptographically-secure RNG there AFAIK...

This issue also exists in these other implementations:
- Java: [implementation](https://github.com/threema-ch/threema-msgapi-sdk-java/blob/3387aaaba0c572d9575c22d5a0e7f65a26b7424c/source/src/main/java/ch/threema/apitool/CryptTool.java#L122-L141), [PRNG](https://docs.oracle.com/javase/7/docs/api/java/util/Random.html#nextInt%28%29)
- PHP: https://github.com/rugk/threema-msgapi-sdk-php/issues/26

Threema was contacted about this issue.

**Comment by lgrahl** [comment]
Solved by a1346801da950f2e00c65f03504dbd56251b329b

**Comment by rugk** [comment]
:+1: 
Nice, also have a look [at these recommendations](https://github.com/jedisct1/libsodium-php/issues/71#issuecomment-166430409). As some might change the padding completly this change of course must be incorporated in all Threema apps and so on and therefore must be discussed with Threema.
