### ISSUE TITLE
Improve decryption of E2E messages

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-msgapi-sdk-python#15]
The decryption functionality of the Python SDK is insufficient. We should at least be able to decrypt messages we are able to send. Missing types:
- `ImageMessage`
- `FileMessage`

Also required for #8

**Comment by lgrahl** [comment]
@maltefiala asked: _Do you plan on releasing an image message decryption support soon? If not, I will start implementing this the following weeks._

**Comment by lgrahl** [comment]
Decryption support is pretty poor at the moment. There is no exception in case the message type is unknown and the message types mentioned in the first post are missing. Also, there are no tests for the `decrypt` method. The answer to your question is: There are no plans yet.

If you want to implement it, this would be my idea: Ideally, most of the spaghetti code in the `send` methods of the various `Message` subclasses should be moved into a `pack` method. For decrypting messages, the constructor would then call the counterpart - an `unpack` method.

**Comment by lgrahl** [comment]
@maltefiala: Have you made any progress or do you need more information, e.g. regarding the packet structure?

**Comment by maltefiala** [comment]
I did not find time to continue process on this side. Is https://github.com/lgrahl/threema-msgapi-sdk-python/pull/14 true? Threema is not able to provide an API with group message support?

**Comment by lgrahl** [comment]
Yes, the problem is that Threema has no way to differentiate between group messages and group control messages (because of E2EE). They believe that gateway users would not be willing to pay for group control messages.
So, technically it is possible but they have no plans on implementing it.

**Comment by maltefiala** [comment]
Ok, I see. Thanks for clarification!
