### ISSUE TITLE
Add Script for libsodium installation

### ISSUE THREAD

**Issue by NeoBelerophon** [threema-ch/threema-msgapi-sdk-python#16]
Hi,

here is a little script to automate libsodium installation on linux systems.
Need to be executed as root:
[install-sodium.txt](https://github.com/lgrahl/threema-msgapi-sdk-python/files/104709/install-sodium.txt)

**Comment by lgrahl** [comment]
Cheers! I'll think about adding it in the next release.

**Comment by 0xE0-rng** [comment]
Thanks a lot for the script, made it all easier

**Comment by rugk** [comment]
@NeoBelerophon

Next time you can use [GitHub gist](https://gist.github.com/) instead of attaching a txt file.
Or... of course... already make a PR.

**Comment by lgrahl** [comment]
A gist would be great. Then I'd simply put a link into the Readme referencing that gist.

**Comment by dbrgn** [comment]
On current distros (like Debian Jessie) you can simply install libsodium via the package manager. Maybe a note about that should be added?

**Comment by lgrahl** [comment]
Can't really write it because my Ubuntu 14 installation is just outdated and I can't test it. If it doesn't hurt, maybe you guys could make a PR? :)

**Comment by rugk** [comment]
It's just a `apt-get install libsodium`. ([current jessie](https://packages.debian.org/jessie/libsodium13), [later sid](https://packages.debian.org/sid/libsodium18))

**Comment by rugk** [comment]
FYI I've also created an [install script for libsodium](https://github.com/rugk/threema-msgapi-sdk-php/blob/master/scripts/buildLibsodium.sh) independent to your own @NeoBelerophon. It is mostly intended to be used for the Travic CI builds, but it could be adjusted to work in general.
@NeoBelerophon Mind having a look and maybe reviewing it?
You can see it in action [in my CI builds](https://travis-ci.org/rugk/threema-msgapi-sdk-php).

**Comment by lgrahl** [comment]
A script for Travis CI will be included with #21 which provides enough hints. Furthermore, I don't think installation of libsodium should be of concern for this module. We're linking to their documentation - that should be sufficient. And furthermore, modern distributions have libsodium in their packages anyway.
