### ISSUE TITLE
Improve public key pinning

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-python#17]
Currently the fingerprint of the certificate is pinned.
There are things to improve this pinning:
1. When cert expires and/or is renewed,. the fingerprint will change, so this breaks clients regularly!
   To prevent this, pin the public key of the key pair instead of the fingerprint.
2. When the key pair has to be changed (e.g. in case of a server breach) there should be a backup key pinned, which can be used in this case. As Threema uses HPKP, they specify one. [More information here](https://github.com/rugk/threema-msgapi-sdk-php/issues/21#issuecomment-247347129).

As this may be an upstream issue with aiohttp, I also opened an issue there: https://github.com/KeepSafe/aiohttp/issues/1187

**Comment by lgrahl** [comment]
Also related: https://github.com/KeepSafe/aiohttp/issues/1185

**Comment by rugk** [comment]
Yeah, but HPKP is about dynamic pinning. This issue here is about a static (hardcoded) pin.

**Comment by rugk** [comment]
Yeah, but HPKP is about dynamic pinning. This issue here is about a static (hardcoded) pin.

**Comment by rugk** [comment]
Another good point made by @thorsteneckel: You still use [SHA-1](https://github.com/lgrahl/threema-msgapi-sdk-python/blob/bed367b9a8775aa1ea2d1972fd1a6cf85798238c/threema/gateway/__init__.py#L86)…

**Comment by lgrahl** [comment]
~~It's not like I have a choice. You should raise that issue towards the aiohttp project. :)~~
Seems this has been changed at some point. You can make a PR as I currently have zero time I can spend on this project.

**Comment by rugk** [comment]
Maybe @thorsteneckel could look into it? I think you've already looked into the code…

**Comment by thorsteneckel** [comment]
I'll take the next free slot of time and create a PR.

**Comment by lgrahl** [comment]
@rugk It was actually MD5 but don't tell anyone. :fearful:
Changed it to SHA256 `a6840a28041a1c43d90c21122ea324272f5c90c82dd64f52701f3a8f1a2b395b`. However, this of course does not resolve the issue of public key pinning.

**Comment by dbrgn** [comment]
@rugk is right about that one, pinning the fingerprint is sometimes not an option in production, since it might break the gateway without notice.

Verifying the public key and backup key (via HPKP) would be the better approach.

@thorsteneckel any news on a free timeslot? :)

**Comment by lgrahl** [comment]
That's why verifying the fingerprint is turned off by default at the moment... which of course isn't ideal.

**Comment by rugk** [comment]
Actually, the aiohttp devs do [not really](https://github.com/aio-libs/aiohttp/issues/1187#issuecomment-389991659) [care](https://github.com/aio-libs/aiohttp/issues/1185#issuecomment-390101331) for that feature here…

Also remember https://github.com/aio-libs/aiohttp/issues/1187 is about _static key pinning_ (what we need here) and https://github.com/aio-libs/aiohttp/issues/1185 about dynamic one (i.e. HPKP). And I would bet I know the argument they'll come up with if you urge them to implement HPKP or implement it yourself in a PR…
