### ISSUE TITLE
Sending Files, File Upload and Download

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-msgapi-sdk-python#3]
The Threema Gateway version 1.1.2 allows sending files and uploading/downloading them to/from the Threema blob server. An update of the Python SDK is required.

**Comment by rugk** [comment]
This was already possible in v1.1.0 - at least this was the version of the [PHP-SDK](https://github.com/rugk/threema-msgapi-sdk-php/commit/54ad6603b5999839dfa4f7d0c647ecf370438baa) - at this time.

**Comment by lgrahl** [comment]
Alright, I didn't know that. Anyhow, we'll implement the missing features in one go and just skip v1.1.0.
