### ISSUE TITLE
Codecov doesn't recognise CLI tests

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-msgapi-sdk-python#32]
I think that was the problem I had with `find_packages` @dbrgn

**Comment by dbrgn** [comment]
Huh? What's the connection?

**Comment by lgrahl** [comment]
I never figured it out but I guess the package was simply ignored by codecov because it wasn't included. Basically, in the tests we call the CLI from subprocess. The lines of the CLI package aren't tracked that way. I had similar issues with the SaltyRTC server (no idea how it has been fixed though).
