### ISSUE TITLE
Update click package to 7.x version

### ISSUE THREAD

**Issue by tbi88** [threema-ch/threema-msgapi-sdk-python#45]
Hi there

Thank you very much for the python-sdk for the threema.gateway. I am facing some dependency issues with click.

You are depending on 'click>=6.7,<7'. Other projects have adapted to click >= 7. 

Would it be possible to update this on your side?

Regards tbi88

**Comment by tbi88** [comment]
I tested it locally with click=7.1.2. Seems to work fine.

**Comment by lgrahl** [comment]
So we can safely bump that dependency then? Good to know. *click* has always one of those trickier ones because they don't seem to follow semantic versioning.

**Comment by tbi88** [comment]
You will still need click, but I have tested it successfully with the latest version (7.1.2)

**Comment by lgrahl** [comment]
Mh, with 7.1.2 some tests fail and `send_e2e` does not work. I'll leave this as is for now since it is low priority for me right now.

However, it's perfectly fine to override the click version in case the gateway API is being used directly instead of using the CLI.

**Comment by RayJW** [comment]
Is this issue still considered low priority? Now that many modern packages have started adopting click >=8.0.0 this is becoming a bigger issue. Click is the one package causing issues for me, but there are actually many outdated dependencies currently required by this project. 
Especially considering that the project still uses a minimal Python version that is EOL [PEP 494](https://peps.python.org/pep-0494/) as of now.

**Comment by lgrahl** [comment]
Hopefully resolved by #61. But I have a high workload for the foreseeable time. PRs to migrate deps welcome.
