### ISSUE TITLE
Long standing py_lru_cache bug.

### ISSUE THREAD

**Issue by NotANormalNerd** [threema-ch/threema-msgapi-sdk-python#46]
Hello and first of all thanks for making this library.

I have a question/suggestion and I was wondering if noone ever ran into this issue.
There is a longstanding bug in py_lru_cache that has not been fixed by now:

https://github.com/stucchio/Python-LRU-cache/pull/18

We went around by pinning to: 'py_lru_cache @ git+https://github.com/kirill578/Python-LRU-cache.git'

**Comment by lgrahl** [comment]
Thanks. I've seen that a couple of times but couldn't reproduce it reliably. I'll bump after a release of the lib.

**Comment by lgrahl** [comment]
I've decided to just move away from that package since it seems unmaintained.
