### ISSUE TITLE
Send ImageMessage with caption

### ISSUE THREAD

**Issue by eknoes** [threema-ch/threema-msgapi-sdk-python#52]
From the Android client it is possible to send an Image with caption. Is that also supported by the API/ this SDK?

**Comment by dbrgn** [comment]
When using the "ImageMessage" type, you can set a caption by using the EXIF comment field in the JPEG. It will be displayed as caption.

That format should still work, but it has been superseded by file messages using a media flag. I think that is not yet supported in this SDK.

**Comment by lgrahl** [comment]
While we could add EXIF modification to the lib, I'd rather supersede those with file messages eventually. @dbrgn's answer is correct and we'll track the file message based variants in #53.
