### ISSUE TITLE
Please publish/tag a release

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-python#6]
Please use the [git tags](https://github.com/lgrahl/threema-msgapi-sdk-python/releases) to [publish releases](https://help.github.com/articles/creating-releases/) of the versions of the Phyton-SDK.

**Comment by lgrahl** [comment]
Will do.

**Comment by rugk** [comment]
As [it seems](https://github.com/lgrahl/threema-msgapi-sdk-python/commit/1cff10044e450435231083e12e538b8d77a587be#diff-46fb613b7f20f2ab36dbab4cc9cdf457R36) you're now v1.1.3 now. :smile: 
So you can publish a release now...

**Comment by rugk** [comment]
You still did not do it...

**Comment by lgrahl** [comment]
Done.

**Comment by rugk** [comment]
Nice you also tagged the old version 1.0. :smiley:
