### ISSUE TITLE
Receive E2E messages

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-msgapi-sdk-python#8]
Receiving E2E messages is already supported (at least the processing part). However, an example is missing, yet. A minimal server implementation which can receive and process incoming E2E messages might be interesting, too.

**Comment by maltefiala** [comment]
Done: https://github.com/Enproduktion/threema-mattermost

**Comment by lgrahl** [comment]
First of all, I'm excited about the use-case you've spotted for the Python Gateway SDK. However, for this project I was thinking of a tiny aiohttp-based solution without having to run nginx or apache.
