### ISSUE TITLE
Public Key Pinning

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-python#9]
If the public key for the HTTPS connected could be pinned, this would certainly improve the security of the TLS connection.

However it seems this is not implemented into Python yet, but [it seems there was at least interest in implementing it](https://bugs.python.org/issue25529).

**Comment by rugk** [comment]
Okay, possibly it is already doable by using the ["verify" setting of requests](https://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror).

**Comment by lgrahl** [comment]
`verify=True` is the default setting (see: http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification)

We could potentially use a certificate fingerprint to improve security after the `requests` module has been replaced by `aiohttp` (see issue #4).

**Comment by rugk** [comment]
I thought more of `verify=cafile`, but this way you may only be able to limit the acceptance to a single CA - not a single certificate.

But if you want to replace `requests` anyway you may also just use `aiohttp`.
In any way it should be optional, so that developers which does not want to use it (and may prefer not to update their software instantly if the HTTPS cert of the MSGAPI server changes) can just use normal TLS verification.

**Comment by lgrahl** [comment]
Implemented in 99cf5498c2bd46f4878f8f2c076b9e1c1df428f3

**Comment by rugk** [comment]
Nice. :+1:

**Comment by lgrahl** [comment]
For anyone chiming in in 2021. In hindsight, this was a mistake. CAs have their flaws but pinning is at least as harmful because it suddenly breaks installations due to the lack of an upgrade flow.
